name: Compile, Build and Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Compile, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Compile
        run: flutter pub get
      - name: Build
        run: flutter build web --release
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.TOKEN_CVCARD }}
          publish_dir: ./build/web
          cname: romanjrdykyj.site

      
